### ISSUE TITLE
quantization

### ISSUE THREAD

**Issue by bbb5317** [TrelisResearch/one-click-llms#1]
from another repo:
Not sure if here is the right place to ask but I wanted to run non quantized. And I thought I can do that by removing the parameter --quantize eetq from the pod custom settings. However I got errors something like - num_heads ... must be divisible by .... I wanted to compare performance between the quantized setup and non quantized. Can you point me in the right direction if I want to run it non quantized with more GPUs offcourse.
The POD used was 3x A6000 48 VRAM, custom settings container disk 150GB, Volume disk 300 GB.

On a side note perhaps a silly question but with Github Desktop how do I get all the branches locally to my HDD? Isn't there an option to somehow get the whole repository with a single click? I ended up downloading them one by one as ZIPs from the web and extracting manually.

**Comment by RonanKMcGovern** [comment]
Thanks! Were you running a specific runpod template from this repo? If so, can you share the URL so I can see the specs.

If not, can you share the full pod details?

**Comment by bbb5317** [comment]
I think this was the link
https://tinyurl.com/3k2ajh44

provided with the video
https://www.youtube.com/watch?v=EXFbZfp8xCI&t=1369s

**Comment by RonanKMcGovern** [comment]
I think the issue is that you're running 3 pods and that is resulting in an issue when dividing the model by 3 to share it across GPUs.

Can you try running either 2 or 4 pods? 2 won't give much room for long context (so you probably need to set the context parameters to be really short).

And yes, for github setup, the best is to log in to github via command line and then do 'git clone' and the repo url in order to copy it to your local. You can then run 'git checkout -b BRANCHNAME' to get a specific branch. I use VSCode for this - may be worth spending some time setting that up with the help of chatgpt.

**Comment by bbb5317** [comment]
Thanks I will try that. Thanks for the github hints I thought the desktop client can do whatever the command line can but obviously not.
Is there a reason for the separation in branches? Can't these simply be folders? I can't have 2 of them open at the same time. It seems git hub is quite unfriendly to allow opening more than 1 branch at the same time.

**Comment by RonanKMcGovern** [comment]
It should be possible to clone a full repo in GitHub desktop too, although I don't use GitHub Desktop. Perhaps chatgpt can help now that you know the github cli approach I mentioned above.

You're right, it may have been better to do folders rather than branches, and I may revert to that in the future.
